branch-defaults:
  eb-setup2:
    environment: res-find-env
    group_suffix: null
global:
  application_name: restaurant-finder-flask
  branch: null
  default_ec2_keyname: s3783461-s3783668-a2cloud
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
